export const amenities: string[] = [
  'Air conditioner',
  'Computerr',
  'Free wireless internet',
  'Game room',
  'Cooking hob',
  'Free Transportation',
  'Guarded parking',
  'Game room',
  'Elevator',
  'Terrace',
  'Blender',
  'Fridge',
  'Fireplace',
  'Balcony',
  'Dishwasher',
  'Freezer',
];
